# Deep learning with pytorch a 60 minute blitz

A official tutorial of pytorch.org

https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html

## Tensors

In [2]:
import torch

x = torch.rand(5, 3)
x

tensor([[0.1723, 0.1178, 0.9082],
        [0.3305, 0.6965, 0.4695],
        [0.8595, 0.8073, 0.9019],
        [0.3212, 0.2302, 0.7329],
        [0.8611, 0.5811, 0.4323]])

In [3]:
x = torch.zeros(5, 3, dtype=torch.long)
x, x.shape, x.dtype

(tensor([[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]), torch.Size([5, 3]), torch.int64)

In [9]:
x1 = x.new_ones(3, 3)
x1, x1.dtype

(tensor([[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]), torch.int64)

In [10]:
x2 = torch.ones_like(x, dtype=torch.float)
x2, x2.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), torch.float32)

In [13]:
x.shape, x.size()

(torch.Size([5, 3]), torch.Size([5, 3]))

### Operations

In [19]:
x = torch.ones(5, 3, dtype=torch.float)
y = torch.rand_like(x, dtype=torch.float)

In [20]:
z = x + y  # torch.add(x, y)
z, z.dtype

(tensor([[1.8307, 1.8036, 1.2400],
         [1.1450, 1.4151, 1.6818],
         [1.6065, 1.0154, 1.2606],
         [1.9564, 1.8080, 1.5959],
         [1.9083, 1.9597, 1.3200]]), torch.float32)

In [22]:
y.add_(x)  # operation in place with underscore

tensor([[1.8307, 1.8036, 1.2400],
        [1.1450, 1.4151, 1.6818],
        [1.6065, 1.0154, 1.2606],
        [1.9564, 1.8080, 1.5959],
        [1.9083, 1.9597, 1.3200]])

In [24]:
z = y.view(-1, 5)
y, z

(tensor([[1.8307, 1.8036, 1.2400],
         [1.1450, 1.4151, 1.6818],
         [1.6065, 1.0154, 1.2606],
         [1.9564, 1.8080, 1.5959],
         [1.9083, 1.9597, 1.3200]]),
 tensor([[1.8307, 1.8036, 1.2400, 1.1450, 1.4151],
         [1.6818, 1.6065, 1.0154, 1.2606, 1.9564],
         [1.8080, 1.5959, 1.9083, 1.9597, 1.3200]]))

In [26]:
y[0, 0], y[0, 0].item()

(tensor(1.8307), 1.8306751251220703)

In [27]:
y[:, 0], y[:, 0].item()

ValueError: only one element tensors can be converted to Python scalars

In [28]:
y[0, 0] = 2.0
y, z

(tensor([[2.0000, 1.8036, 1.2400],
         [1.1450, 1.4151, 1.6818],
         [1.6065, 1.0154, 1.2606],
         [1.9564, 1.8080, 1.5959],
         [1.9083, 1.9597, 1.3200]]),
 tensor([[2.0000, 1.8036, 1.2400, 1.1450, 1.4151],
         [1.6818, 1.6065, 1.0154, 1.2606, 1.9564],
         [1.8080, 1.5959, 1.9083, 1.9597, 1.3200]]))

### Numpy bridge

In [29]:
a = torch.ones(5)
b = a.numpy()
a.add_(1)
a, b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

In [32]:
b = b + 1
a, b

(tensor([2., 2., 2., 2., 2.]), array([3., 3., 3., 3., 3.], dtype=float32))

In [33]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

## Autograd: automatic differentiation

https://m0nads.wordpress.com/2019/04/10/pytorchs-backward-function/

In [7]:
import torch

x = torch.ones(2, 2, requires_grad=True)
# x = torch.ones(2, 2)
# x[1, 1] = 2
# x.requires_grad = True
y = x + 2
z = y * y *3
out = z.mean()
x, y, z, out

(tensor([[1., 1.],
         [1., 1.]], requires_grad=True), tensor([[3., 3.],
         [3., 3.]], grad_fn=<AddBackward0>), tensor([[27., 27.],
         [27., 27.]], grad_fn=<MulBackward0>), tensor(27., grad_fn=<MeanBackward0>))

In [8]:
out.backward()
x.grad

# torch.autograd.grad(outputs=out, inputs=x)

(tensor([[4.5000, 4.5000],
         [4.5000, 4.5000]]),)

#### vector jacobian product

The backward op works for a scalar output

In [67]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
x, y

(tensor([ 0.2023, -0.6989, -0.5675], requires_grad=True),
 tensor([  414.3698, -1431.3527, -1162.3149], grad_fn=<MulBackward0>))

In [68]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

still torch.autograd can compute the vector-Jacobian product.

\begin{equation}
J = \frac{\partial y}{\partial x} = \frac{\partial y_i}{\partial x_j}
\end{equation}

\begin{equation}
{\bar x} = J^T {\bar y}
\end{equation}

In [69]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
x.grad

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])

In [77]:
x = torch.tensor([[1.0, 2], [3, 4]], requires_grad=True)
y = x + 2
z = y * y * 3
z

tensor([[ 27.,  48.],
        [ 75., 108.]], grad_fn=<MulBackward0>)

In [78]:
# v = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
v = torch.ones(2, 2)
z.backward(v)
x, v, z, x.grad

(tensor([[1., 2.],
         [3., 4.]], requires_grad=True), tensor([[1., 1.],
         [1., 1.]]), tensor([[ 27.,  48.],
         [ 75., 108.]], grad_fn=<MulBackward0>), tensor([[18., 24.],
         [30., 36.]]))