## Unscented transform

In [2]:
import numpy as np
from scipy import linalg

In [5]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html

m = np.array([12.3, 7.6])
P = np.array([[1.44, 0], [0, 2.89]])

In [6]:
linalg.sqrtm(P)

array([[1.2, 0. ],
       [0. , 1.7]])

In [52]:
alpha = 1e-1
beta = 2
kappa = 0

L = 2

lambda_ = alpha**2 * (L + kappa) - L
lambda_

-1.98

In [53]:
Chi = [0]
Chi += [np.sqrt((L + lambda_)*1.44), np.sqrt((L + lambda_)*2.89)]
Chi += [-np.sqrt((L + lambda_)*1.44), -np.sqrt((L + lambda_)*2.89)]
Chi = np.array([m + w for w in Chi])

W_0m = [lambda_/(L + lambda_)]
W_0m += [1.0 / 2.0 / (L + lambda_)] * 4
W_0c = [lambda_/(L + lambda_) + (1 - alpha**2 + beta)]
W_0c += [1.0 / 2.0 / (L + lambda_)] * 4

W_0m = np.array(W_0m)
W_0c = np.array(W_0c)

The transformation function to polar coordinates,

\begin{align}
r &= \sqrt{x^2 + y^2} \\
\theta &= \arctan{ \frac{y}{x} }
\end{align}

In [55]:
def transform(xy):
    x, y = xy[0], xy[1]
    return np.sqrt(x**2 + y**2), np.arctan(y / x)

rtheta = np.array(list(map(transform, Chi[:])))
rtheta

array([[14.45856148,  0.5534674 ],
       [14.6922389 ,  0.55722215],
       [14.78966426,  0.55875161],
       [14.22509459,  0.54958933],
       [14.12788134,  0.54793565]])

In [56]:
rtheta_mean = sum([W_0m[i] * rtheta[i, :] for i in range(5)])
rtheta_mean

array([14.47439091,  0.54419659])

In [57]:
rtheta_del = rtheta - rtheta_mean
rtheta_del

array([[-0.01582943,  0.00927081],
       [ 0.217848  ,  0.01302556],
       [ 0.31527335,  0.01455502],
       [-0.24929632,  0.00539274],
       [-0.34650957,  0.00373906]])

In [58]:
sum([W_0c[i] * np.outer(rtheta_del[i,:], rtheta_del[i,:]) for i in range(5)])

array([[8.20275707e+00, 1.33749386e-01],
       [1.33749386e-01, 2.36255301e-03]])